ERROR_CODE_NO_ERROR = 0
ERROR_CODE_LIB_ERROR = 1
ERROR_CODE_NETWORK_ERROR = 501
ERROR_CODE_LOGIN_FAILED = 502
ERROR_CODE_UNAVAILABLE = 503
ERROR_CODE_TIMEOUT = 504
ERROR_CODE_LOCKED = 423
ERROR_CODE_GAME_LOGIC_ERROR = 1001
ERROR_CODE_DUPLICATE_USER_NAME = 1100
# Unable to register because symbols are included.
ERROR_CODE_UNAVAILABLE_WORDS = 1101
ERROR_CODE_ENERGY_FULL = 1102
ERROR_CODE_NOT_ENOUGH_LOVECA = 1103
ERROR_CODE_NOT_ENOUGH_GAME_COIN = 1104
# Inappropriate words contained.
ERROR_CODE_NG_WORDS = 1105
# Name could not be changed
ERROR_CODE_ONLY_WHITESPACE_CHARACTERS = 1106
ERROR_CODE_OVER_UNIT_MAX = 1108
ERROR_CODE_OVER_FRIEND_MAX = 1109
ERROR_CODE_CHARACTER_COUNT_IS_OVER = 1112
ERROR_CODE_OVER_ADD_WAITING_UNIT_MAX_LIMIT = 1114
ERROR_CODE_NO_RECOVER_ITEM = 1130
ERROR_CODE_RECOVER_ITEM_NOT_ENOUGH = 1131
ERROR_CODE_ITEM_EXPIRED = 1140
ERROR_CODE_INCENTIVE_NONE = 1201
ERROR_CODE_OPEN_OTHERS = 1202
ERROR_CODE_LIMIT_OVER = 1203
ERROR_CODE_NOT_RELEASE_LOTTERY_TICKET = 1204
ERROR_CODE_NO_UNIT_IS_SELLABLE = 1205
ERROR_CODE_DUPLICATE_UNIT = 1301
ERROR_CODE_NO_CENTER_UNIT = 1302
ERROR_CODE_POSITION_EMPTY = 1303
ERROR_CODE_IGNORE_MAIN_DECK = 1304
ERROR_CODE_IGNORE_MAIN_DECK_UNIT = 1305
ERROR_CODE_NO_GAME_COIN = 1306
ERROR_CODE_UNIT_NOT_EXIST = 1311
ERROR_CODE_UNIT_NOT_DISPOSE = 1312
ERROR_CODE_UNIT_LEVEL_AND_SKILL_LEVEL_MAX = 1313
ERROR_CODE_IGNORE_FAVORITE_FLAG = 1321
ERROR_CODE_ACCESSORY_LOTTERY_LIST_HAS_DIFFERENCE = 1353
ERROR_CODE_BATTLE_ROOM_IS_INVALID = 1400
ERROR_CODE_BATTLE_DIFFICULTY_NOT_FOUND = 1401
ERROR_CODE_BATTLE_NPC_NOT_MATCHED = 1402
ERROR_CODE_BATTLE_NOT_EXIST = 1403
ERROR_CODE_EVENT_BATTLE_LIVE_NOT_FOUND = 1404
ERROR_CODE_EVENT_BATTLE_NEED_END_WAIT = 1405
ERROR_CODE_SECRET_BOX_NOT_EXIST = 1500
ERROR_CODE_SECRET_BOX_COST_TYPE_IS_NOT_SPECIFIED = 1501
ERROR_CODE_SECRET_BOX_INVALID_COST_TYPE = 1502
ERROR_CODE_SECRET_BOX_NOT_MULTI = 1503
ERROR_CODE_SECRET_BOX_AUTHORITY_ERROR = 1504
ERROR_CODE_SECRET_BOX_GAUGE_INFORMATION_NOT_EXIST = 1505
ERROR_CODE_SECRET_BOX_GAUGE_IS_FULL = 1506
ERROR_CODE_SECRET_BOX_REMAINING_COST_IS_NOT_ENOUGH = 1507
ERROR_CODE_SECRET_BOX_OUT_OF_DATE = 1508
ERROR_CODE_SECRET_BOX_UPPER_LIMIT = 1509
ERROR_CODE_SECRET_BOX_INVALID_TERM_COUNT = 1510
ERROR_CODE_SECRET_BOX_OUT_OF_DATE_PICK_UP_SCHEDULE = 1511
ERROR_CODE_SECRET_BOX_OUT_OF_STAMP_TERM = 1512
ERROR_CODE_SECRET_BOX_NO_AVAILABLE_SUBSCRIPTION = 1513
ERROR_CODE_USER_NOT_EXIST = 1601
# Ranking data hasn't yet been calculated.
ERROR_CODE_OUT_OF_RANG = 1602
ERROR_CODE_INVISIBLE_LIVE_INFO = 1603
INITIAL_DECK_NOT_EXISTS = 1701
INITIAL_MAIN_DECK_ALREADY_EXIST = 1702
ERROR_ALLIANCE_DUMMY = 1900
ERROR_ALLIANCE_DUMMY2 = 1901
ERROR_ALLIANCE_DUMMY3 = 1902
ERROR_CODE_SCENARIO_NOT_FOUND = 2300
ERROR_CODE_SCENARIO_NOT_AVAILABLE = 2301
ERROR_CODE_SCENARIO_LIVE_IS_PLAYING = 2302
ERROR_CODE_SCENARIO_NO_REWARD = 2303
ERROR_CODE_SCENARIO_IS_CLOSED = 2304
ERROR_CODE_SCENARIO_HAS_GOAL = 2305
ERROR_CODE_SUBSCENARIO_NOT_FOUND = 2350
ERROR_CODE_SUBSCENARIO_NOT_AVAILABLE = 2351
ERROR_CODE_SUBSCENARIO_LIVE_IS_PLAYING = 2352
ERROR_CODE_SUBSCENARIO_NO_REWARD = 2353
ERROR_CODE_SUBSCENARIO_IS_CLOSED = 2354
ERROR_CODE_EVENT_SCENARIO_HAS_ALREADY_OPENED = 2385
ERROR_CODE_EVENT_LACK_OF_COST = 2386
# The Academy Student you specified doesn't exist.
ERROR_CODE_FRIEND_USER_NOT_EXISTS = 2400
ERROR_CODE_FRIEND_SPECIFIED_USER_IS_NOT_A_FRIEND = 2401
ERROR_CODE_FRIEND_SPECIFIED_USER_IS_ARLEADY_FRIEND = 2402
ERROR_CODE_FRIEND_NOT_REQUESTED_FROM_SPECIFIED_USER = 2403
ERROR_CODE_FRIEND_NOT_REQUESTING_TO_SPECIFIED_USER = 2404
ERROR_CODE_FRIEND_COUNT_OVER_LIMIT = 2405
ERROR_CODE_FRIEND_ALREADY_REQUESTING_TO_SPECIFIED_USER = 2406
ERROR_CODE_FRIEND_ALREADY_REJECTED_FROM_SPECIFIED_USER = 2407
ERROR_CODE_FRIEND_ALREADY_CANCELED_FROM_SPECIFIED_USER = 2408
ERROR_CODE_FRIEND_COUNT_OVER_LIMIT_OF_APPLICANT = 2409
ERROR_CODE_FRIEND_OVER_REQUEST_COUNT = 2410
ERROR_CODE_FRIEND_OVER_PENDING_APPROVAL_COUNT = 2411
ERROR_CODE_GREET_INVALID_CHARACTOR = 2500
ERROR_CODE_ALBUM_REWARD_NONE = 2700
ERROR_CODE_ALBUM_REWARD_OPENED = 2701
ERROR_CODE_TUTORIAL_MAKE_FIRST_DECK_ERROR = 3000
ERROR_CODE_TUTORIAL_OPEN_FIRST_SCENARIO_ERROR = 3001
ERROR_CODE_TUTORIAL_SET_USER_SETTING_ERROR = 3002
ERROR_CODE_TUTORIAL_OPEN_FIRST_LIVE_ERROR = 3003
ERROR_CODE_TUTORIAL_BAD_STATE_ERROR = 3004
ERROR_CODE_TUTORIAL_IS_END = 3005
ERROR_CODE_SNS_COIN_LIMIT_OVER = 3100
ERROR_CODE_PAYMENT_INVALID_APPLE_PRODUCT_ID = 3101
# The Live Show you specified is not available.
ERROR_CODE_LIVE_NOT_FOUND = 3400
# Required LP exceeds max LP
ERROR_CODE_LIVE_NOT_ENOUGH_MAX_ENERGY = 3401
# You don't have enough LP.
ERROR_CODE_LIVE_NOT_ENOUGH_CURRENT_ENERGY = 3402
ERROR_CODE_LIVE_NOT_ENOUGH_LOVECA = 3403
ERROR_CODE_LIVE_INVALID_PARTY_USER = 3404
ERROR_CODE_LIVE_INVALID_UNIT_DECK = 3405
ERROR_CODE_LIVE_UNIT_LIMIT_OVER = 3406
ERROR_CODE_LIVE_NOTES_LEVEL_RATE_NOT_FOUND = 3407
ERROR_CODE_LIVE_NOTES_EFFECT_NOT_FOUND = 3408
ERROR_CODE_LIVE_UNIT_REWARD_NOT_FOUND = 3409
ERROR_CODE_LIVE_PARTY_MEMBER_INFO_NOT_FOUND = 3410
ERROR_CODE_LIVE_PLAY_DATA_NOT_FOUND = 3411
# You don't have enough <token name>.
ERROR_CODE_LIVE_NOT_ENOUGH_EVENT_POINT = 3412
ERROR_CODE_LIVE_NOT_MATCH_LIVE_RANK = 3413
# An error has occured. Please reboot.
ERROR_CODE_LIVE_UNKNOWN_ERROR = 3414
ERROR_CODE_LIVE_LEADER_SKILL_NOT_FOUND = 3415
ERROR_CODE_LIVE_NOTES_LIST_NOT_FOUND = 3416
# The Live Show you specified is not available.
ERROR_CODE_LIVE_NOT_OPENED = 3417
# This event is not in progress.
ERROR_CODE_LIVE_EVENT_HAS_GONE = 3418
ERROR_CODE_LIVE_UNEXPECTED_END = 3419
# No record is available
ERROR_CODE_LIVE_PRECISE_LIST_NOT_FOUND = 3421
ERROR_CODE_LIVE_RETRY = 3422
# Use <amount of money> G to recover one past Master song play?
ERROR_CODE_LIVE_NOT_ENOUGH_TRAINING_ENERGY = 3423
# There are no past Master song plays remaining.
# The amount will reset at midnight JST.
ERROR_CODE_LIVE_NOT_ENOUGH_TRAINING_ENERGY_CANT_RECOVERY = 3424
ERROR_CODE_LIVE_MATCHING_NO_ROOM = 3450
ERROR_CODE_LIVE_MATCHING_ROOM_FULL = 3451
ERROR_CODE_LIVE_MATCHING_USER_NOT_ENOUGH = 3452
ERROR_CODE_LIVE_MATCHING_CANNOT_LEAVE = 3453
ERROR_CODE_LIVE_MATCHING_INVALID_TERM = 3454
ERROR_CODE_LIVE_GPS_MATCHING_NOT_OPENED = 3455
ERROR_CODE_LIVE_MATCHING_STATUS_UPDATED = 3456
ERROR_CODE_LIVE_MATCHING_DISMISS = 3457
ERROR_CODE_LIVE_POLLING_DISMISS = 3459
ERROR_CODE_LIVE_MATCHING_CANNOT_OPEN = 3460
ERROR_CODE_LIVE_ARENA_MATCH_NOT_AUTO_PLAYABLE = 3470
ERROR_CODE_LIVE_ARENA_MATCH_AUTO_PLAYABLE = 3471
ERROR_CODE_LIVE_ARENA_MATCH_NO_LIVE_PRECISE_LOG = 3472
ERROR_CODE_LIVE_ARENA_MATCH_LIVE_PRECISE_LOG_UPDATED = 3473
ERROR_CODE_LIVE_ARENA_MATCH_USER_NOT_FOUND = 3474
ERROR_CODE_LIVE_ARENA_MATCH_USER_RATING_UPDATED = 3475
ERROR_CODE_LIVE_ARENA_DREAM_SESSION_EXPIRED = 3480
ERROR_CODE_LIVE_ARENA_DREAM_SESSION_NOT_MEET_PLAY_REQUIREMENTS = 3481
# Exchange limit reached.
ERROR_CODE_OVER_ADD_EXCHANGE_ITEM_COUNT_MAX_LIMIT = 4201
# You do not have enough <exchange currency>.
ERROR_CODE_NOT_ENOUGH_EXCHANGE_POINT = 4202
# This item has expired.
ERROR_CODE_EXCHANGE_ITEM_OUT_OF_DATE = 4203
# Sticker shop is currently unavailable! Please try again later.
ERROR_CODE_EXCHANGE_INVALID = 4204
# No longer valid.
ERROR_CODE_EXCHANGE_POINT_OUT_OF_DATE = 4215
ERROR_CODE_NOT_ACTIVE_DISCOUNT_LICENSE = 4216
ERROR_CODE_AWARD_ALREADY_GAINED = 4205
ERROR_CODE_BACKGROUND_ALREADY_GAINED = 4206
ERROR_CODE_AWARD_IS_CONTAINED_IN_BOX = 4207
ERROR_CODE_BACKGROUND_IS_CONTAINED_IN_BOX = 4208

# This Transfer Passcode is expired.
ERROR_HANDOVER_EXPIRE = 4401
# This Transfer Passcode is incorrect.
ERROR_HANDOVER_NONE = 4402
# You can't transfer data within the same device, nor if you still have purchased items such as :Loveca:Love Gems.
ERROR_HANDOVER_SELF = 4403
# This passcode has already been used.
ERROR_HANDOVER_DISABLE_MU = 4404
# Game data can't be transferred from this account.
# Please wait for a while and try again.
ERROR_HANDOVER_LOCKED_USER = 4405
# Game data can't be transferred to this account.
# Please wait for a while and try again.
ERROR_HANDOVER_LOCKED_TARGET = 4406
# Invaid Transfer ID or Transfer Passcode.
# Please try again.
ERROR_HANDOVER_INVALID_ID_OR_CODE = 4407
# You can't transfer your game data to a different OS as you still have Love Gems and/or purchased Scouting Tickets.
ERROR_HANDOVER_PAYMENT_ITEM_POSSESSION = 4408

# SIF ID cannot be accessed at this time.
ERROR_KLAB_ID_SERVICE_NOT_AVAILABLE = 4490
# Please log in again.
ERROR_KLAB_ID_SERVICE_LOGIN_AGAIN = 4491
# SIF ID is currently under maintenance.
ERROR_KLAB_ID_SERVICE_MAINTENANCE = 4492
# There is no Love Live! School Idol Festival game data registered to this SIF ID account.
ERROR_KLAB_ID_SERVICE_NOT_REGISTERED = 4493
# There is a Love Live! School Idol Festival game data registered to this SIF ID account.
# Registered game data can be removed from Menu > Settings.
ERROR_KLAB_ID_SERVICE_ALREADY_REGISTERED = 4494
# A data mismatch was found.
# You may be logged in to the incorrect SIF ID.
ERROR_KLAB_ID_SERVICE_NOT_MATCH = 4495
# An unexpected error has occured.
ERROR_KLAB_ID_SERVICE_NOT_HAS_ENOUGH_SCOPE = 4496
# An unexpected error has occured.
ERROR_KLAB_ID_SERVICE_TASK_DISABLED = 8001

ERROR_CODE_ONLINE_PLAY_COUNT_LIMIT_OVER = 4701
ERROR_CODE_ONLINE_LIVE_HAS_GONE = 4702
ERROR_CODE_FINAL_VOTE_OUT_TERM = 4710
ERROR_CODE_FINAL_NO_RESULT = 4720
ERROR_CODE_FINAL_MAINTENANCE = 4740
ERROR_DOWNLOAD_NO_ADDITIONAL_PACKAGE = 4501
ERROR_DOWNLOAD_NO_UPDATE_PACKAGE = 4502
ERROR_CODE_EVENT_REWARD_OPENED = 10000
ERROR_CODE_EVENT_REWARD_NOT_GETTABLE = 10001
ERROR_CODE_EVENT_NO_EVENT_POINT_COUNT_DATA = 10002
ERROR_CODE_EVENT_NO_EVENT_POINT_USER_DATA = 10003
ERROR_CODE_EVENT_NO_EVENT_DATA = 10004
ERROR_CODE_LL_ACCOUNT_ALREADY_CONNECTED = 6000
ERROR_CODE_PF_ACCOUNT_ALREADY_CONNECTED = 6001
ERROR_CODE_CONNECTION_DOSE_NOT_EXISTS = 6002
ERROR_CODE_INVALID_USERS_HANDOVER = 6003
ERROR_CODE_INVALID_PLATFORM_HANDOVER = 6004
ERROR_CODE_STAMP_TYPE_UNDEFINED = 6100
ERROR_CODE_STAMP_SETTING_ID_INVALID = 6101
ERROR_CODE_STAMP_COUNT = 6103
ERROR_CODE_STAMP_TYPE_MISS_MATCH = 6104
ERROR_CODE_STAMP_DUPLICATE_POSITION = 6105
ERROR_CODE_STAMP_DUPLICATE_STAMP = 6106
ERROR_CODE_STAMP_NOT_OWNED = 6107
ERROR_CODE_STAMP_NO_MAIN = 6108
ERROR_CODE_AC_MAINT = 11101
ERROR_CODE_AC_NO_DATA = 11102
ERROR_CODE_AREA_ALREADY_RECEIVED = 4801
ERROR_CODE_AREA_OUT_OF_AREA = 4802
ERROR_CODE_AREA_OUT_OF_DATE = 4803
ERROR_CODE_AREA_EXCEEDED_POSSESSION_LIMIT = 4804
ERROR_CODE_SNS_ALREADY_RECEIVED = 5001
ERROR_CODE_SNS_OUT_OF_DATE = 5002
ERROR_CODE_SNS_ALREADY_HAS_NON_DUPLICABLE_ITEM = 5003
ERROR_CODE_FESTIVAL_MISSION_EXPIRED = 9902
ERROR_CODE_ITEM_USE_USED_ITEM = 21001
ERROR_CODE_ITEM_USE_OUT_OF_EVENT = 21002
ERROR_CODE_CLASS_CHALLENGE_LIVE_TERM_OVER = 7100
ERROR_CODE_NO_AD_REWARD_REST = 13001
ERROR_CODE_NO_SKIT_AVAILABLE = 14001
ERROR_CODE_RECEIPT_FAIL_ACKNOWLEDGE = 22001
ERROR_CODE_LOOT_BOX_EXPIRE = 23001
ERROR_CODE_DELETE_RESERVED_USER = 25001
ERROR_CODE_DELETED_USER = 25002


class IdolError(Exception):
    def __init__(
        self, error_code: int = 200, status_code: int = 720, detail: str | None = None, *, http_code: int = 200
    ) -> None:
        self.error_code = error_code
        self.status_code = status_code
        self.detail = detail
        self.http_code = http_code


def by_code(code: int):
    return IdolError(code, 600)


def locked():
    return IdolError(423, 600, "F", http_code=423)
