services:
  npps4:
    image: ghcr.io/darkenergyprocessor/npps4:latest
    environment:
      NPPS4_WORKER: 1
    ports:
      - 51376:51376
    volumes:
      - ./data:/data
    restart: unless-stopped
