import enum

from . import ADD_TYPE

# https://w.atwiki.jp/lovelive-sif/pages/38.html
LIVE_EXP_DROP = [12, 26, 43, 83]
LIVE_GOLD_DROP = [
    [2250, 1800, 1200, 600, 300],
    [3000, 2400, 1600, 800, 400],
    [3750, 3000, 2000, 1000, 500],
    [4500, 3600, 2400, 1200, 600],
]

SUBSCENARIO_LOVECA_REWARD_AMOUNT = 1
SUBSCENARIO_GAME_COIN_REWARD_AMOUNT = 20000
SUBSCENARIO_REWARD_COMMENT_EN = "Side story cleared!"
SUBSCENARIO_REWARD_COMMENT_JP = "サイドストーリークリア！"


class SECRETBOX_COST_TYPE(enum.IntEnum):
    NON_COST = 0
    LOVECA = 3001
    ITEM_TICKET = 1000
    FRIEND = 3002
    FREE_TICKET = 100
    GAME_COIN = 3000


class SECRETBOX_LAYOUT_TYPE(enum.IntEnum):
    DEFAULT = 0
    STEP_UP = 1
    EXTRA = 2
    BOX = 3
    BOX_TYPE = 4
    STUB = 5
    SELECT = 6
    LUCKY_BAG = 8
    SELECT_UNIT = 9
    PICKUP_BOOST = 10


class SECRETBOX_BUTTON_TYPE(enum.IntEnum):
    DEFAULT_SINGLE = 1
    DEFAULT_MULTI = 2
    MULTI_COST = 3
    LIMIT_SINGLE = 4
    LIMIT_MULTI = 5
    NORMAL_FREE = 6
    NORMAL_SINGLE = 7
    NORMAL_MULTI = 8
    STUB_A = 9
    STUB_B = 10
    STUB_C = 11
    FREE_SINGLE = 12
    FREE_MULTI = 13
    DEFAULT_TICKET_SINGLE = 14
    DEFAULT_TICKET_MULTI1 = 15
    DEFAULT_TICKET_MULTI2 = 16
    LIMIT_TICKET_SINGLE = 17
    LIMIT_TICKET_MULTI1 = 18
    LIMIT_TICKET_MULTI2 = 19


class SECRETBOX_ANIMATION_TYPE(enum.IntEnum):
    DEFAULT_TYPE_A = 1
    DEFAULT_TYPE_B = 2
    SIMPLE = 3
    SELECT = 4
    BOX_TYPE_A = 5
    BOX_TYPE_B = 6
    DEFAULT_TYPE_C = 7


class SECRETBOX_STAMP_REWARD_TYPE(enum.IntEnum):
    ITEM = 1
    FIX_RARITY_ORIGINAL_PROB = 2
    FIX_PICK_UP_CONSTANT = 3
    COST = 4
    FIX_PICK_UP_ORIGINAL_PROB = 6
    ADDITIONAL_FIX_RARITY_CONSTANT = 7
    ADDITIONAL_FIX_PICK_UP_CONSTANT = 8
