"""empty message

Revision ID: b15644c599d7
Revises: f575fa1caf58
Create Date: 2023-10-27 16:07:56.710674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b15644c599d7"
down_revision: Union[str, None] = "f575fa1caf58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incentive",
        sa.Column("id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("add_type", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("insert_date", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("expire_date", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("incentive", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incentive_insert_date"), ["insert_date"], unique=False)

    op.create_table(
        "incentive_unit_option",
        sa.Column("id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("is_signed", sa.Boolean(), nullable=False),
        sa.Column("exp", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("skill_exp", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("max_level", sa.Integer(), nullable=False),
        sa.Column("love", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("display_rank", sa.Integer(), nullable=False),
        sa.Column("level_limit_id", sa.Integer(), nullable=False),
        sa.Column("unit_removable_skill_capacity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["incentive.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("incentive_unit_option")
    with op.batch_alter_table("incentive", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incentive_insert_date"))

    op.drop_table("incentive")
    # ### end Alembic commands ###
