"""empty message

Revision ID: f575fa1caf58
Revises: 15c72c5be7e7
Create Date: 2023-10-20 19:54:10.756076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f575fa1caf58"
down_revision: Union[str, None] = "15c72c5be7e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_bonus",
        sa.Column("id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "year", "month", "day"),
    )
    with op.batch_alter_table("login_bonus", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_login_bonus_day"), ["day"], unique=False)
        batch_op.create_index(batch_op.f("ix_login_bonus_month"), ["month"], unique=False)
        batch_op.create_index(batch_op.f("ix_login_bonus_year"), ["year"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("login_bonus", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_login_bonus_year"))
        batch_op.drop_index(batch_op.f("ix_login_bonus_month"))
        batch_op.drop_index(batch_op.f("ix_login_bonus_day"))

    op.drop_table("login_bonus")
    # ### end Alembic commands ###
