"""empty message

Revision ID: 15c72c5be7e7
Revises: ba4f2c510cae
Create Date: 2023-10-19 11:18:52.466349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "15c72c5be7e7"
down_revision: Union[str, None] = "ba4f2c510cae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "live_effort",
        sa.Column("user_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("live_effort_point_box_spec_id", sa.Integer(), nullable=False),
        sa.Column("current_point", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    with op.batch_alter_table("achievement", schema=None) as batch_op:
        batch_op.add_column(sa.Column("achievement_type", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("is_new", sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f("ix_achievement_achievement_id"), ["achievement_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_achievement_achievement_type"), ["achievement_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_achievement_end_date"), ["end_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_achievement_insert_date"), ["insert_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_achievement_is_new"), ["is_new"], unique=False)
        batch_op.create_index(batch_op.f("ix_achievement_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("album", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_album_love_max_flag"), ["love_max_flag"], unique=False)
        batch_op.create_index(batch_op.f("ix_album_rank_level_max_flag"), ["rank_level_max_flag"], unique=False)
        batch_op.create_index(batch_op.f("ix_album_rank_max_flag"), ["rank_max_flag"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("album", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_album_rank_max_flag"))
        batch_op.drop_index(batch_op.f("ix_album_rank_level_max_flag"))
        batch_op.drop_index(batch_op.f("ix_album_love_max_flag"))

    with op.batch_alter_table("achievement", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_achievement_user_id"))
        batch_op.drop_index(batch_op.f("ix_achievement_is_new"))
        batch_op.drop_index(batch_op.f("ix_achievement_insert_date"))
        batch_op.drop_index(batch_op.f("ix_achievement_end_date"))
        batch_op.drop_index(batch_op.f("ix_achievement_achievement_type"))
        batch_op.drop_index(batch_op.f("ix_achievement_achievement_id"))
        batch_op.drop_column("is_new")
        batch_op.drop_column("achievement_type")

    op.drop_table("live_effort")
    # ### end Alembic commands ###
