"""Implement museum unlock.

Revision ID: f098df3fb07e
Revises: fd3ea1f6d982
Create Date: 2023-12-26 12:43:19.067467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f098df3fb07e"
down_revision: Union[str, None] = "fd3ea1f6d982"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "museum_unlock",
        sa.Column("id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("museum_contents_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "museum_contents_id"),
    )
    with op.batch_alter_table("museum_unlock", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_museum_unlock_museum_contents_id"), ["museum_contents_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_museum_unlock_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("museum_unlock", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_museum_unlock_user_id"))
        batch_op.drop_index(batch_op.f("ix_museum_unlock_museum_contents_id"))

    op.drop_table("museum_unlock")
    # ### end Alembic commands ###
