"""Initial unit (deck) table

Revision ID: 580779c07e41
Revises: 02293a9b6387
Create Date: 2023-10-14 13:58:07.194489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "580779c07e41"
down_revision: Union[str, None] = "02293a9b6387"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unit",
        sa.Column("id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("favorite_flag", sa.Boolean(), nullable=False),
        sa.Column("is_signed", sa.Boolean(), nullable=False),
        sa.Column("insert_date", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("exp", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("max_level", sa.Integer(), nullable=False),
        sa.Column("love", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("display_rank", sa.Integer(), nullable=False),
        sa.Column("level_limit_id", sa.Integer(), nullable=False),
        sa.Column("unit_removable_skill_capacity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("unit", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_unit_active"), ["active"], unique=False)
        batch_op.create_index(batch_op.f("ix_unit_user_id"), ["user_id"], unique=False)

    op.create_table(
        "unit_deck",
        sa.Column("id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("deck_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "deck_number"),
    )
    with op.batch_alter_table("unit_deck", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_unit_deck_deck_number"), ["deck_number"], unique=False)
        batch_op.create_index(batch_op.f("ix_unit_deck_user_id"), ["user_id"], unique=False)

    op.create_table(
        "unit_deck_position",
        sa.Column("id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("deck_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.ForeignKeyConstraint(
            ["deck_id"],
            ["unit_deck.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deck_id", "unit_id"),
    )
    with op.batch_alter_table("unit_deck_position", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_unit_deck_position_deck_id"), ["deck_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_unit_deck_position_unit_id"), ["unit_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("unit_deck_position", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_unit_deck_position_unit_id"))
        batch_op.drop_index(batch_op.f("ix_unit_deck_position_deck_id"))

    op.drop_table("unit_deck_position")
    with op.batch_alter_table("unit_deck", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_unit_deck_user_id"))
        batch_op.drop_index(batch_op.f("ix_unit_deck_deck_number"))

    op.drop_table("unit_deck")
    with op.batch_alter_table("unit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_unit_user_id"))
        batch_op.drop_index(batch_op.f("ix_unit_active"))

    op.drop_table("unit")
    # ### end Alembic commands ###
