"""Remove unnecessary fields in album

Revision ID: ea53ebe430a5
Revises: 70ac54a8641d
Create Date: 2023-10-15 10:34:06.111592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ea53ebe430a5"
down_revision: Union[str, None] = "70ac54a8641d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("album", schema=None) as batch_op:
        batch_op.drop_column("all_max_flag")
        batch_op.drop_column("total_love")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("album", schema=None) as batch_op:
        batch_op.add_column(sa.Column("total_love", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("all_max_flag", sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
