"""ADd skill_exp to unit

Revision ID: fe18ce373a0d
Revises: 3634b82cf75d
Create Date: 2023-10-14 15:35:03.029469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe18ce373a0d"
down_revision: Union[str, None] = "3634b82cf75d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("unit", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("skill_exp", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("unit", schema=None) as batch_op:
        batch_op.drop_column("skill_exp")

    # ### end Alembic commands ###
