"""Add album, supporter, and center

Revision ID: 70ac54a8641d
Revises: fe18ce373a0d
Create Date: 2023-10-15 10:13:07.318109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70ac54a8641d"
down_revision: Union[str, None] = "fe18ce373a0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "album",
        sa.Column("id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("unit_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("rank_max_flag", sa.Boolean(), nullable=False),
        sa.Column("love_max_flag", sa.Boolean(), nullable=False),
        sa.Column("rank_level_max_flag", sa.Boolean(), nullable=False),
        sa.Column("all_max_flag", sa.Boolean(), nullable=False),
        sa.Column("highest_love_per_unit", sa.Integer(), nullable=False),
        sa.Column("total_love", sa.Integer(), nullable=False),
        sa.Column("favorite_point", sa.Integer(), nullable=False),
        sa.Column("sign_flag", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("album", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_album_unit_id"), ["unit_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_album_user_id"), ["user_id"], unique=False)

    op.create_table(
        "unit_supporter",
        sa.Column("id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("unit_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("amount", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "unit_id"),
    )
    with op.batch_alter_table("unit_supporter", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_unit_supporter_unit_id"), ["unit_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_unit_supporter_user_id"), ["user_id"], unique=False)

    op.create_table(
        "unit_center",
        sa.Column("user_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("unit_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["unit.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    with op.batch_alter_table("unit_center", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_unit_center_unit_id"), ["unit_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("unit_center", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_unit_center_unit_id"))

    op.drop_table("unit_center")
    with op.batch_alter_table("unit_supporter", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_unit_supporter_user_id"))
        batch_op.drop_index(batch_op.f("ix_unit_supporter_unit_id"))

    op.drop_table("unit_supporter")
    with op.batch_alter_table("album", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_album_user_id"))
        batch_op.drop_index(batch_op.f("ix_album_unit_id"))

    op.drop_table("album")
    # ### end Alembic commands ###
