"""empty message

Revision ID: 612bdd685d1a
Revises: b15644c599d7
Create Date: 2023-11-07 23:23:27.450171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "612bdd685d1a"
down_revision: Union[str, None] = "b15644c599d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incentive", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incentive_add_type"), ["add_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_incentive_expire_date"), ["expire_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_incentive_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incentive", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incentive_user_id"))
        batch_op.drop_index(batch_op.f("ix_incentive_expire_date"))
        batch_op.drop_index(batch_op.f("ix_incentive_add_type"))

    # ### end Alembic commands ###
