"""empty message

Revision ID: f8b44a48b0ef
Revises: 3c0c34f09192
Create Date: 2024-08-18 13:41:01.349881

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8b44a48b0ef"
down_revision: Union[str, None] = "3c0c34f09192"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("achievement", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reset_type", sa.Integer(), nullable=False, server_default=sa.text("0")))
        batch_op.add_column(
            sa.Column(
                "reset_value",
                sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"),
                nullable=False,
                server_default=sa.text("0"),
            )
        )
        batch_op.create_index(batch_op.f("ix_achievement_reset_type"), ["reset_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_achievement_reset_value"), ["reset_value"], unique=False)

    with op.batch_alter_table("achievement", schema=None) as batch_op:
        batch_op.alter_column("reset_type", nullable=False, server_default=None)
        batch_op.alter_column("reset_value", nullable=False, server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("achievement", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_achievement_reset_value"))
        batch_op.drop_index(batch_op.f("ix_achievement_reset_type"))
        batch_op.drop_column("reset_value")
        batch_op.drop_column("reset_type")

    # ### end Alembic commands ###
