"""Add insert_date to SIS table

Revision ID: 853c5b3ae7ba
Revises: 4a18a6d96722
Create Date: 2024-02-02 10:52:37.792880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "853c5b3ae7ba"
down_revision: Union[str, None] = "4a18a6d96722"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("removable_skill_info", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("insert_date", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("removable_skill_info", schema=None) as batch_op:
        batch_op.drop_column("insert_date")

    # ### end Alembic commands ###
