"""Fixes table

Revision ID: deea55d98599
Revises: 6a6186e47091
Create Date: 2025-08-30 12:37:34.686999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "deea55d98599"
down_revision: Union[str, None] = "6a6186e47091"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "migration_fixes", sa.Column("revision", sa.Text(), nullable=False), sa.PrimaryKeyConstraint("revision")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("migration_fixes")
    # ### end Alembic commands ###
