"""empty message

Revision ID: 6a6186e47091
Revises: d701309ff89e
Create Date: 2025-05-04 13:07:24.508384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a6186e47091"
down_revision: Union[str, None] = "d701309ff89e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_ranking",
        sa.Column("id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("score", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "day"),
    )
    with op.batch_alter_table("player_ranking", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_player_ranking_user_id"),
            [sa.text("user_id ASC"), sa.text("day DESC"), sa.text("score DESC")],  # type: ignore
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_ranking", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_player_ranking_user_id"))

    op.drop_table("player_ranking")
    # ### end Alembic commands ###
