"""empty message

Revision ID: 397436128a36
Revises: 930ed8d00ec1
Create Date: 2024-04-05 14:43:34.696856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "397436128a36"
down_revision: Union[str, None] = "930ed8d00ec1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

UNIQUE_CONSTRAINT_ITEM_NAME = "uq_item_user_id_item_id"
UNIQUE_CONSTRAINT_RECOVERY_ITEM_NAME = "uq_recovery_item_user_id_item_id"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.drop_index("ix_item_user_id")
        batch_op.create_index(batch_op.f("ix_item_user_id"), ["user_id"], unique=False)
        batch_op.create_unique_constraint(UNIQUE_CONSTRAINT_ITEM_NAME, ["user_id", "item_id"])

    with op.batch_alter_table("recovery_item", schema=None) as batch_op:
        batch_op.drop_index("ix_recovery_item_user_id")
        batch_op.create_index(batch_op.f("ix_recovery_item_user_id"), ["user_id"], unique=False)
        batch_op.create_unique_constraint(UNIQUE_CONSTRAINT_RECOVERY_ITEM_NAME, ["user_id", "item_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recovery_item", schema=None) as batch_op:
        batch_op.drop_constraint(UNIQUE_CONSTRAINT_ITEM_NAME, type_="unique")
        batch_op.drop_index(batch_op.f("ix_recovery_item_user_id"))
        batch_op.create_index("ix_recovery_item_user_id", ["user_id"], unique=1)

    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.drop_constraint(UNIQUE_CONSTRAINT_RECOVERY_ITEM_NAME, type_="unique")
        batch_op.drop_index(batch_op.f("ix_item_user_id"))
        batch_op.create_index("ix_item_user_id", ["user_id"], unique=1)

    # ### end Alembic commands ###
