"""empty message

Revision ID: 930ed8d00ec1
Revises: 58d5edd4f818
Create Date: 2024-04-05 14:41:45.322772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "930ed8d00ec1"
down_revision: Union[str, None] = "58d5edd4f818"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange_point_item",
        sa.Column("id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("exchange_point_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "exchange_point_id"),
    )
    with op.batch_alter_table("exchange_point_item", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exchange_point_item_exchange_point_id"), ["exchange_point_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_exchange_point_item_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exchange_point_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exchange_point_item_user_id"))
        batch_op.drop_index(batch_op.f("ix_exchange_point_item_exchange_point_id"))

    op.drop_table("exchange_point_item")
    # ### end Alembic commands ###
