"""empty message

Revision ID: 5039725fabc6
Revises: fea75afe02ba
Create Date: 2024-03-12 18:58:06.611228

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5039725fabc6"
down_revision: Union[str, None] = "fea75afe02ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request_cache",
        sa.Column("id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("nonce", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("response", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "nonce"),
    )
    with op.batch_alter_table("request_cache", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_request_cache_nonce"), ["nonce"], unique=False)
        batch_op.create_index(batch_op.f("ix_request_cache_user_id"), ["user_id"], unique=False)

    op.create_table(
        "session",
        sa.Column("id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("user_id", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=True),
        sa.Column("client_key", sa.LargeBinary(), nullable=False),
        sa.Column("server_key", sa.LargeBinary(), nullable=False),
        sa.Column("last_accessed", sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session")
    with op.batch_alter_table("request_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_request_cache_user_id"))
        batch_op.drop_index(batch_op.f("ix_request_cache_nonce"))

    op.drop_table("request_cache")
    # ### end Alembic commands ###
