"""empty message

Revision ID: b3d6a058fa62
Revises: deea55d98599
Create Date: 2025-10-11 18:32:01.082342

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3d6a058fa62"
down_revision: Union[str, None] = "deea55d98599"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "game_coin",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "game_coin",
            existing_type=sa.BigInteger().with_variant(sa.INTEGER(), "sqlite"),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
